"""change_events

Revision ID: 5a0f71442838
Revises: d99b29557678
Create Date: 2026-06-11 11:10:49.269565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0f71442838'
down_revision: Union[str, Sequence[str], None] = 'd99b29557678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_events_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_device_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_change_events_change_type'))

    op.drop_table('change_events')
    # ### end Alembic commands ###
