"""initial schema

Revision ID: d99b29557678
Revises: 
Create Date: 2026-06-09 14:57:48.432245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99b29557678'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('current_user', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('ram_total_gb', sa.Float(), nullable=True),
    sa.Column('ram_free_gb', sa.Float(), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('disk_c_free_gb', sa.Float(), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('internet_ok', sa.Boolean(), nullable=False),
    sa.Column('glpi_status', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_freq_mhz', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_used_percent', sa.Float(), nullable=True),
    sa.Column('alert_disk_min_free_gb', sa.Float(), nullable=True),
    sa.Column('alert_ram_min_free_gb', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)

    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('fields_schema', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_categories_name'), ['name'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('disk_min_free_gb', sa.Float(), nullable=False),
    sa.Column('offline_after_minutes', sa.Integer(), nullable=False),
    sa.Column('ui_theme', sa.String(length=32), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('alert_email_to', sa.String(length=512), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)

    op.create_table('device_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_used_percent', sa.Float(), nullable=True),
    sa.Column('disk_used_percent', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_snapshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('alerts_detected', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostics_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostics_id'), ['id'], unique=False)

    op.create_table('disk_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('mount_point', sa.String(length=16), nullable=False),
    sa.Column('total_gb', sa.Float(), nullable=True),
    sa.Column('free_gb', sa.Float(), nullable=True),
    sa.Column('percent_used', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disk_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disk_info_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_info_id'), ['id'], unique=False)

    op.create_table('installed_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installed_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installed_programs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installed_programs_id'), ['id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_id'), ['id'], unique=False)

    op.create_table('power_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('power_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)

    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_history_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_history_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_history_id'))

    op.drop_table('inventory_history')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_device_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('power_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_power_events_id'))
        batch_op.drop_index(batch_op.f('ix_power_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_power_events_device_id'))

    op.drop_table('power_events')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_category_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('installed_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installed_programs_id'))
        batch_op.drop_index(batch_op.f('ix_installed_programs_device_id'))

    op.drop_table('installed_programs')
    with op.batch_alter_table('disk_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disk_info_id'))
        batch_op.drop_index(batch_op.f('ix_disk_info_device_id'))

    op.drop_table('disk_info')
    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostics_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostics_device_id'))

    op.drop_table('diagnostics')
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_device_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_device_snapshots_device_id'))

    op.drop_table('device_snapshots')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_device_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_code'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('inventory_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_categories_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_categories_id'))

    op.drop_table('inventory_categories')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))

    op.drop_table('devices')
    # ### end Alembic commands ###
