"""add glpi settings

Revision ID: e8beea789622
Revises: 5a0f71442838
Create Date: 2026-06-11 13:29:28.277753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8beea789622'
down_revision: Union[str, Sequence[str], None] = '5a0f71442838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glpi_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('glpi_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('glpi_app_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('glpi_user_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('glpi_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('glpi_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('glpi_password')
        batch_op.drop_column('glpi_username')
        batch_op.drop_column('glpi_user_token')
        batch_op.drop_column('glpi_app_token')
        batch_op.drop_column('glpi_url')
        batch_op.drop_column('glpi_enabled')

    # ### end Alembic commands ###
